---
- hosts: k8smy
  tasks:
  - name: br_netfilter install and
    shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        br_netfilter
        EOF

        modprobe br_netfilter

        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
---
- hosts: k8smy
  tasks:
  - name: br_netfilter install and
    shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        br_netfilter
        EOF

        modprobe br_netfilter

        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        vm.swappiness=0
        EOF

        sysctl --system

  - name: install docker
    shell: |
        yum install -y yum-utils && yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        yum install docker-ce -y


  - name: 配置docker cgroup 管理方式为systemd
    shell: |
        mkdir /etc/docker
        cat <<EOF | sudo tee /etc/docker/daemon.json
        {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
        "max-size": "100m"
        },
        "storage-driver": "overlay2"
        }
        EOF

  - name: 安装 kubeadm kubectl kubelet
    shell: |
        cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
        exclude=kubelet kubeadm kubectl
        EOF

        yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

        systemctl enable --now kubelet

  - name: 关闭swap
    shell: swapoff -a && sed -i /swap/d /etc/fstab

  - name: ssh 互信
    shell: echo "you show do something"
